require('chromedriver');

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

const chrome = require('selenium-webdriver/chrome');
const chromedriver = require('chromedriver');

chrome.setDefaultService(new chrome.ServiceBuilder(chromedriver.path).build());


describe('by e vignette', function () {
    this.timeout(30000)
    let driver
    beforeEach(async function () {
        driver = new Builder().forBrowser('chrome').build();
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('by e vignette', async function () {
        await driver.manage().window().setRect({ width: 2000, height: 2000 })
        await driver.get("https://www.a1.bg/bg")
        await driver.findElement(By.xpath("//a/figure/figcaption[text() = 'е-Винетка']/../..")).click()
        const kupiTukUrl = await driver.findElement(By.xpath("//a[text() = 'Купи тук']"))   // grab the location of link to prevent opening in new tab
        await driver.get(await kupiTukUrl.getAttribute('href'))   // navigate to new location instead of opening a new tab
        await driver.findElement(By.xpath("//*[@id=\"ico1\"]")).click()
        await driver.findElement(By.xpath("//*[@id=\"priceTag-4\"]")).click()
        await driver.findElement(By.xpath("//*[@id=\"plate\"]")).sendKeys("CA1234BT")
        await driver.findElement(By.xpath("//*[@id=\"startFrom2\"]")).click()
        await driver.findElement(By.xpath("//*[@id=\"ui-datepicker-div\"]/table/tbody//a[contains(@class, \'ui-state-highlight\')]")).click()
        await driver.findElement(By.xpath("//*[@id=\"paymentBtn\"]/button[2]")).click()
        await driver.findElement(By.xpath("//*[@id=\"email\"]")).sendKeys("ivo92@abv.bg")
        await driver.findElement(By.xpath("//*[@id=\"page\"]/main/div/div/div/div[2]/div/div[6]/label/var")).click()
        await driver.findElement(By.xpath("//*[@id=\"paymentBtn\"]/button[2]")).click()
        await driver.wait(until.elementLocated(By.xpath("//*[@id=\"confirmVignetteData\"]/div[2]/div/div[2]/div[2]/table/tbody/tr[1]/td[2]")), 10000);
        assert(await driver.findElement(By.xpath("//*[@id=\"confirmVignetteData\"]/div[2]/div/div[2]/div[2]/table/tbody/tr[1]/td[2]")).getText() == "CA1234BT")
        assert(await driver.findElement(By.xpath("//*[@id=\"confirmVignetteData\"]/div[2]/div/div[2]/div[2]/table/tbody/tr[4]/td[2]")).getText() == "Лек автомобил до 3,5 тона")
        await driver.findElement(By.xpath("//*[@id=\"confirmVignetteData\"]/div[2]/div/div[2]/div[6]/button[2]")).click()
        await driver.wait(until.elementLocated(By.xpath("//*[starts-with(text(),\'Покупка на винетка\')]")), 10000)
        const description = await driver.findElement(By.xpath("//*[starts-with(text(),\'Покупка на винетка\')]")).getText()
        assert(description.includes("Покупка на винетка"))
    })
})

